title: FleetOptimiser OS2 Documentation
description: The documentation of FleetOptimiser OS2
theme: just-the-docs

url: https://just-the-docs.github.io

logo: /assets/fologos.png

aux_links:
  FleetOptimiser OS2: https://github.com/OS2fleetoptimiser/OS2fleetoptimiser

plugins:
  - jekyll-relative-links